export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SAVE_ALL_POSTS = 'SAVE_ALL_POSTS';
export const SET_POST_DETAIL = 'SET_POST_DETAIL';
export const SAVE_EDITED_POST = 'SAVE_EDITED_POST';
export const SAVE_NEW_POST = 'SAVE_NEW_POST';
export const DELETE_POST = 'DELETE_POST';
export const SAVE_EDITED_COMMENT = 'SAVE_EDITED_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';






